export enum CrudViewColumnType {
  DateTime = 'datetime',
  Date = 'date',
  Tag = 'tag',
  Icon = 'icon',
  Text = 'text',
  Boolean = 'boolean',
  Number = 'number',
  Link = 'link',
  Image = 'image',
  Currency = 'currency',
  Rate = 'rate',
  Switch = 'switch',
  ActionLink = 'action-link',
}
